// materialIconsList.ts
export const materialIconNames = [  
  "restaurant",
  "home",
  "shopping-cart",
  "car-crash",
  "category",
  "directions-bus",
  "directions-car",
  "payments",
  "paid",
  "credit-card",
  "school",
  "work",
  "family-restroom",
  "apartment",
  "account-balance",
  "favorite",
  "favorite-border",
  "star",
  "stars",
  "star-border",
  "loyalty",
  "checkroom",
  "auto-stories",
  "description",
  "note",
  "request-page",
  "sports-soccer",
  "sports-basketball",
  "sports-baseball",


];
